title: typo
favicon: /icon.svg
icon: /icon.svg

menu:
  archives: /archives
  about: /about

copyright: Kytolly(shiroi)
mathjax: true
heading_numbering: true

# Image settings
image:
  enable: true  # Master switch
  center: true  # Center images
  caption: true # Display alt text as caption with numbering
