title: Kytolly's Blog
favicon: /icon.svg
icon: /icon.svg

menu:
  index: / 
  archive: /archive
  tag: /tag
  about: /about

copyright: Kytolly(shiroi)

# mathjax support
mathjax: true

# heading numbering
heading_numbering: true

# Table style for markdown data tables
three_line_table: true

# Image settings
image:
  enable: true  # Master switch
  center: true  # Center images
  caption: true # Display alt text as caption with numbering


# codeblock
code_block:
  copy_button: icon/copy.svg
  
  # Theme toggling for code blocks
  # Requires `light_theme` and `dark_theme` to be enabled.
  theme_toggle:
    enable: true
    to_light_button: icon/light.svg
    to_dark_button: icon/dark.svg
    light_theme: css/vscode-modern-light.css
    dark_theme: css/vscode-modern-dark.css
  mac_enhancier: 
    enable: true
    init_folded_status: true

# Table of Contents (TOC) settings
toc:
  enable: true
  position: left # Options: left, right

local_search:
  enable: true

background:
  enable: true
  folder: img/
  opacity: 0.1
  position: center
  size: cover
  repeat: no-repeat
  image: 
    mode: random # or pointed
    count: 113 # only used when mode is random
    name: background.jpg # only used when mode is pointed